#! /bin/sh

# load resources for X from a custom file instead of using .Xresources and .Xdefaults
# use -merge for combining multiple files
xrdb .Xrc

# turn off DPMS (no screen blackout)
xset -dpms

# load sxhkd
sxhkd -m -1 &

# load Compton
compton -b

# set compose key to menu
setxkbmap us -option compose:menu

# load Lemonbar

#~/.config/lemonbar/lemonrc.sh | lemonbar -p &

# load Telegram
~/prog/Telegram/Telegram &

# bspc setup

bspc monitor DVI-I-2 -d I II III IV 
bspc monitor DVI-I-1 -d V VI VII VIII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# colors
bspc config focused_border_color \#FF9900

# change background image  
while :; do feh --bg-fill --randomize ~/Pictures/Wallpapers/*; sleep 1h; done &
